version: 2.4
project_name: smd

builds:
  - id: smd
    main: ./cmd/smd/
    binary: smd
    ldflags:
      - "-X main.GitCommit={{.Commit}} \
         -X main.BuildTime={{.Timestamp}} \
         -X main.Version={{.Version}} \
         -X main.GitBranch={{.Branch}} \
         -X main.GitTag={{.Tag}} \
         -X main.GitState={{ .Env.GIT_STATE }} \
         -X main.BuildHost={{ .Env.BUILD_HOST }} \
         -X main.GoVersion={{ .Env.GO_VERSION }} \
         -X main.BuildUser={{ .Env.BUILD_USER }} "
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v3
    env:
      - CGO_ENABLED=0

  - id: smd-init
    main: ./cmd/smd-init/
    binary: smd-init
    ldflags:
      - "-X main.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v3
    env:
      - CGO_ENABLED=0

  - id: smd-loader
    main: ./cmd/smd-loader/
    binary: smd-loader
    ldflags:
      - "-X main.Version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
    goamd64:
      - v3
    env:
      - CGO_ENABLED=0

dockers:
  - image_templates:
      - "ghcr.io/openchami/{{.ProjectName}}:{{ .Tag }}-amd64"
      - "ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}-amd64"
      - "ghcr.io/openchami/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/openchami/{{.ProjectName}}:latest"
    use: buildx
    goos: linux
    goarch: amd64
    goamd64: v3
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - LICENSE
      - CHANGELOG.md
      - README.md
      - migrations/

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
