# Copyright 2019-2020 Hewlett Packard Enterprise Development LP

FROM cray/smd-base

# Run test coverage...
RUN set -ex && \
    go test -cover -v stash.us.cray.com/HMS/hms-smd/cmd/smd && \
    go test -cover -v stash.us.cray.com/HMS/hms-smd/internal/./... && \
    go test -cover -v stash.us.cray.com/HMS/hms-smd/pkg/./...
